#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port7,           clawmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armmotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveFoward(int timeMoving) {

	motor[leftmotor] = 60;
	motor[rightmotor] = 60;
	wait1Msec(timeMoving);

}

task main()
{

 moveForward(1000);
 moveForwad(5000);

}
